Add upload / download variable toggle
jaymoulin/docker-google-musicmanager pull request #9
Opened 2018-05-30 13:19 UTC by Undeadhunter

Add option to enable/disable upload/download

2018-05-30 14:59 UTC, jaymoulin commented
Thanks for your contribution. If you suggested it because you wanted to upload/download only, please make sure you acknowledged existence of both side projects :

# Uploader
https://github.com/jaymoulin/docker-google-music-uploader
https://hub.docker.com/r/jaymoulin/google-music-uploader/

# Downloader
https://github.com/jaymoulin/docker-google-music-downloader
https://hub.docker.com/r/jaymoulin/google-music-downloader/

--

As I understand it could be useful to transform an existing container to a downloader/uploader only without generating another key/device, I may accept this PR

2018-05-30 15:02 UTC, jaymoulin requested changes
PIDD and PIDU are now declared in a condition. Make sure those are correctly declared in other cases

2018-05-30 15:02 UTC, jaymoulin commented on daemon.sh
>      wait $PIDD
Please be aware that this variable doesn't exist in all cases

2018-05-30 15:02 UTC, jaymoulin commented on daemon.sh
>      wait $PIDU
Please be aware that this variable doesn't exist in all cases

2018-05-30 18:13 UTC, Undeadhunter commented on daemon.sh
>      wait $PIDU
I assume adding the wait into the IF would work. 

Unless you prefer to make another IF true and put them in there?

2018-05-30 18:14 UTC, Undeadhunter commented
Did not know those existed! Thanks!

2018-05-30 19:35 UTC, jaymoulin commented on daemon.sh
>      wait $PIDU
Adding the wait in the if should work but take care of keeping the double wait (it's a feature, not a bug ;)) and name the variable `$PIDU` for uploader et `$PIDD` for download

2018-05-30 19:54 UTC, Undeadhunter commented
All fixed

2018-05-30 20:37 UTC, jaymoulin commented
Do you mind update `README.md` to document this feature and squash all commits (with mine) to have a meaningful contribution?

2018-05-31 10:52 UTC, Undeadhunter commented
That should be it, never done any squashing, so hope it's good now.

2018-05-31 23:00 UTC, jaymoulin approved these changes

2018-05-31 23:12 UTC, merged

2018-05-31 23:17 UTC, jaymoulin commented
Thanks for your contribution ;)

2018-06-11 11:32 UTC, Undeadhunter commented
I noticed the FALSE isn't taken correctly, will check it out later this week.